### ISSUE TITLE
Replace httpjson input with http and configure tag_keys

### ISSUE THREAD

**Issue by Sharpie** [puppetlabs/puppet_metrics_dashboard#61]
The `httpjson` input used by the current Telegraf configuration is deprecated as of Telegraf 1.6. We should switch over to using the `http` input:

```toml
[[inputs.http]]
  data_format = json
  ...
```

We should also use the JSON parser's support for the `tag_keys` parameter to appropriately tag metrics arrays such as those produced by Puppet Server's `master` and `puppet-profiler` sections.
